apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-exporter
  namespace: pod-exporter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-exporter
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-exporter
subjects:
- kind: ServiceAccount
  name: pod-exporter
  namespace: pod-exporter
roleRef:
  kind: ClusterRole
  name: pod-exporter
  apiGroup: rbac.authorization.k8s.io
